services:
  rathena:
    container_name: "rathena"
    image: rathena
    pull_policy: never
    env_file: .env
    volumes:
      - ./rathena/repository_override:/opt/repository_override
    build:
      context: ./rathena
      args:
          PACKETVER: ${PACKETVER}
          SET_PRERENEWAL: ${SET_PRERENEWAL}
          PACKET_OBFUSCATION_KEY1: ${PACKET_OBFUSCATION_KEY1}
          PACKET_OBFUSCATION_KEY2: ${PACKET_OBFUSCATION_KEY2}
          PACKET_OBFUSCATION_KEY3: ${PACKET_OBFUSCATION_KEY3}
          MARIADB_HOST: ${MARIADB_HOST}
          MARIADB_DATABASE: ${MARIADB_DATABASE}
          MARIADB_USER: ${MARIADB_USER}
          MARIADB_PASSWORD: ${MARIADB_PASSWORD}
          SET_MOTD: ${SET_MOTD}
          SET_INTERSRV_USER: ${SET_INTERSRV_USER}
          SET_INTERSRV_PASSWORD: ${SET_INTERSRV_PASSWORD}
    entrypoint: sh -c ". /usr/local/bin/docker-entrypoint.sh && setup_database"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend

  ragnarok-login:
    container_name: "ragnarok-login"
    image: rathena
    restart: always
    pull_policy: never
    user: ragnarok:ragnarok
    #volumes:
    #  - ./rathena/repository:/opt/ragnarok
    command: /opt/ragnarok/login-server
    tty: true
    depends_on:
      rathena:
        condition: service_completed_successfully
    ports:
      - 6900:6900
    networks:
      - backend

  ragnarok-char:
    container_name: "ragnarok-char"
    image: rathena
    restart: always
    pull_policy: never
    user: ragnarok:ragnarok
    #volumes:
    #  - ./rathena/repository:/opt/ragnarok
    command: /opt/ragnarok/char-server
    tty: true
    depends_on:
      ragnarok-login:
        condition: service_started
    ports:
      - 6121:6121
    networks:
      - backend

  ragnarok-map:
    container_name: "ragnarok-map"
    image: rathena
    restart: always
    pull_policy: never
    user: ragnarok:ragnarok
    #volumes:
    #  - ./rathena/repository:/opt/ragnarok
    command: /opt/ragnarok/map-server
    tty: true
    depends_on:
      ragnarok-char:
        condition: service_started
    ports:
      - 5121:5121
    networks:
      - backend

networks:
  backend:
