services:
  database:
    container_name: "database"
    image: mariadb:11.8.6
    restart: always
    env_file: .env
    #ports:
    #  - 3306:3306
    volumes:
      # Uncomment line below to use on volume
      #- ./database/data:/var/lib/mysql
      - ./database/conf.d:/etc/mariadb.conf.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mariadb --user=$${MARIADB_USER} --password=$${MARIADB_PASSWORD} --execute 'SELECT 1;'"]
      start_period: 10s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend

  wsproxy:
    container_name: "wsproxy"
    image: ghcr.io/raiken-mf/wsproxy:1.2.32
    restart: always
    command: ["-a", "ragnarok_login:6900,ragnarok_char:6121,ragnarok_map:5121"]
    tty: true
    ports:
      - 5999:5999
    networks:
      - backend

  robrowser:
    container_name: "robrowser"
    image: ghcr.io/raiken-mf/robrowser:2.0.0
    restart: always
    env_file: .env
    volumes:
      - ./client/AI:/opt/client_files/AI:ro
      - ./client/BGM:/opt/client_files/BGM:ro
      - ./client/data:/opt/client_files/data:ro
      - ./client/System:/opt/client_files/System:ro
      - ./client/resources:/opt/client_files/resources:ro
    tty: true
    depends_on:
      - wsproxy
    ports:
      - "${PORT_HTTP:-8080}:80"
      - "${PORT_FRONTEND:-3000}:3000"
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend:
