services:
  database:
    container_name: "database"
    image: mariadb:11.8.6
    restart: always
    env_file: .env
    #ports:
    #  - 3306:3306
    volumes:
      # Uncomment line below to use on volume
      #- ./database/data:/var/lib/mysql
      - ./database/conf.d:/etc/mariadb.conf.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mariadb --user=$${MARIADB_USER} --password=$${MARIADB_PASSWORD} --execute 'SELECT 1;'"]
      start_period: 10s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend

  wsproxy:
    container_name: "wsproxy"
    image: ghcr.io/raiken-mf/wsproxy:${WSPROXY_IMAGE_TAG:-stable}
    restart: always
    command: ["-a", "ragnarok-login:6900,ragnarok-char:6121,ragnarok-map:5121"]
    tty: true
    ports:
      - "${PORT_WSPROXY:-5999}:5999"
    networks:
      - backend

  robrowser:
    container_name: "robrowser"
    image: ghcr.io/raiken-mf/robrowser:${ROBROWSER_IMAGE_TAG:-stable}
    pull_policy: always
    restart: always
    env_file: .env
    volumes:
      - ./client/AI:/opt/client_files/AI:ro
      - ./client/BGM:/opt/client_files/BGM:ro
      - ./client/data:/opt/client_files/data:ro
      - ./client/System:/opt/client_files/System:ro
      - ./client/resources:/opt/client_files/resources:ro
    build:
      context: .
      dockerfile: robrowser/Dockerfile
      args:
        SET_PRERENEWAL: ${SET_PRERENEWAL}
        ROBROWSER_REPOSITORY: ${ROBROWSER_REPOSITORY:-https://github.com/raiken-mf/roBrowserLegacy.git}
        ROBROWSER_REF: ${ROBROWSER_REF:-2f114a1f3dc0e9721e45c4731420ee2417e00fe4}
        ROENGLISH_REPOSITORY: ${ROENGLISH_REPOSITORY:-https://github.com/raiken-mf/ROenglishRE.git}
        ROENGLISH_REF: ${ROENGLISH_REF:-fc674823d7830d0ff75b73c79c99caf640af5a0e}
    tty: true
    depends_on:
      - wsproxy
    ports:
      - "${PORT_HTTP:-8080}:8080"
      - "${PORT_FRONTEND:-3000}:3000"
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend:
