site_name: roBrowser Docker Stack
site_description: Documentation for roBrowser, rAthena and Kubernetes Deployment
repo_url: https://github.com/raiken-mf/robrowser_docker
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - content.code.copy