apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - network-policy.yaml
  - pvc-client-data.yaml
  - mariadb.yaml
  - rathena.yaml
  - robrowser.yaml
  - wsproxy.yaml
