apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: ${MARIADB_HOST}
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: ${MARIADB_HOST}
    app.kubernetes.io/part-of: ragnarok-stack
spec:
  replicas: 1

  galera:
    enabled: false

  image: mariadb:11.8.6
  imagePullPolicy: IfNotPresent

  rootPasswordSecretKeyRef:
    name: mariadb-root-secret
    key: password

  storage:
    size: 5Gi
    storageClassName: longhorn

  myCnf: |
    [mysqld]
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    default-time-zone='+00:00'

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1024Mi

  service:
    type: ClusterIP
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: ${MARIADB_DATABASE}
  namespace: ${NAMESPACE}
spec:
  mariaDbRef:
    name: ${MARIADB_HOST}
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: ${MARIADB_USER}
  namespace: ${NAMESPACE}
spec:
  mariaDbRef:
    name: ${MARIADB_HOST}
  passwordSecretKeyRef:
    name: mariadb-user-secret
    key: password
  maxUserConnections: 50
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: ${MARIADB_USER}-grant
  namespace: ${NAMESPACE}
spec:
  mariaDbRef:
    name: ${MARIADB_HOST}
  privileges:
    - "ALL PRIVILEGES"
  database: "${MARIADB_DATABASE}"
  table: "*"
  username: "${MARIADB_USER}"
  grantOption: false
