apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ragnarok

resources:
  - ../../k8s

patches:
  - target:
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/labels/app.kubernetes.io~1name
        value: ragnarok
  - target:
      kind: NetworkPolicy
      name: allow-db-rathena-only
    patch: |-
      - op: replace
        path: /spec/podSelector/matchLabels/app.kubernetes.io~1name
        value: mariadb
  - target:
      group: k8s.mariadb.com
      kind: MariaDB
    patch: |-
      - op: replace
        path: /metadata/name
        value: mariadb
      - op: replace
        path: /metadata/labels/app.kubernetes.io~1name
        value: mariadb
  - target:
      group: k8s.mariadb.com
      kind: Database
    patch: |-
      - op: replace
        path: /metadata/name
        value: ragnarok
      - op: replace
        path: /spec/mariaDbRef/name
        value: mariadb
  - target:
      group: k8s.mariadb.com
      kind: User
    patch: |-
      - op: replace
        path: /metadata/name
        value: ragnarok-user
      - op: replace
        path: /spec/mariaDbRef/name
        value: mariadb
  - target:
      group: k8s.mariadb.com
      kind: Grant
    patch: |-
      - op: replace
        path: /metadata/name
        value: ragnarok-user-grant
      - op: replace
        path: /spec/mariaDbRef/name
        value: mariadb
      - op: replace
        path: /spec/database
        value: ragnarok
      - op: replace
        path: /spec/username
        value: ragnarok-user
  - target:
      kind: Deployment
      name: ragnarok-login
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/0/command/2
        value: 'until nc -z -v -w3 mariadb 3306; do echo "Waiting for Database..."; sleep 2; done;'
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/raiken-mf/rathena:stable # {"$imagepolicy": "flux-system:rathena"}
  - target:
      kind: Deployment
      name: ragnarok-char
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/raiken-mf/rathena:stable # {"$imagepolicy": "flux-system:rathena"}
  - target:
      kind: Deployment
      name: ragnarok-map
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/raiken-mf/rathena:stable # {"$imagepolicy": "flux-system:rathena"}
  - target:
      kind: Service
      name: robrowser
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30000
      - op: replace
        path: /spec/ports/1/nodePort
        value: 30080
  - target:
      kind: Deployment
      name: robrowser
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/raiken-mf/robrowser:stable # {"$imagepolicy": "flux-system:robrowser"}
  - target:
      kind: Service
      name: wsproxy
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30599
  - target:
      kind: Deployment
      name: wsproxy
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/raiken-mf/wsproxy:stable # {"$imagepolicy": "flux-system:wsproxy"}
