apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: client-data
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 15Gi
