apiVersion: apps/v1
kind: Deployment
metadata:
  name: robrowser
  namespace: ragnarok
  labels:
    app.kubernetes.io/name: robrowser
    app.kubernetes.io/part-of: ragnarok-stack
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: robrowser
  template:
    metadata:
      labels:
        app.kubernetes.io/name: robrowser
        app.kubernetes.io/part-of: ragnarok-stack
    spec:
      containers:
        - name: robrowser
          image: ghcr.io/raiken-mf/robrowser:2.0.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: robrowser-config
          ports:
            - name: http-backend
              containerPort: 80
            - name: http-frontend
              containerPort: 3000
          volumeMounts:
            - name: client-data
              mountPath: /opt/client_files/resources
              subPath: resources
            - name: client-data
              mountPath: /opt/client_files/BGM
              subPath: BGM
            - name: client-data
              mountPath: /opt/client_files/AI
              subPath: AI
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 2048Mi
      volumes:
        - name: client-data
          persistentVolumeClaim:
            claimName: client-data
---
apiVersion: v1
kind: Service
metadata:
  name: robrowser
  namespace: ragnarok
  labels:
    app.kubernetes.io/name: robrowser
    app.kubernetes.io/part-of: ragnarok-stack
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: robrowser
  ports:
    - name: http-backend
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
    - name: http-frontend
      port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
