apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsproxy
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: wsproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wsproxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wsproxy
    spec:
      containers:
        - name: wsproxy
          image: ghcr.io/raiken-mf/wsproxy:1.2.32
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "5999"
            - name: RAG_LOGIN_HOST
              value: "ragnarok-login"
            - name: RAG_LOGIN_PORT
              value: "6900"
            - name: RAG_CHAR_HOST
              value: "ragnarok-char"
            - name: RAG_CHAR_PORT
              value: "6121"
            - name: RAG_MAP_HOST
              value: "ragnarok-map"
            - name: RAG_MAP_PORT
              value: "5121"
          ports:
            - containerPort: 5999
              name: wsproxy
---
apiVersion: v1
kind: Service
metadata:
  name: wsproxy
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: wsproxy
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: wsproxy
  ports:
    - name: wsproxy
      port: 5999
      targetPort: 5999
      nodePort: 30599
