apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: rathena
  namespace: flux-system
spec:
  image: ghcr.io/raiken-mf/rathena
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: robrowser
  namespace: flux-system
spec:
  image: ghcr.io/raiken-mf/robrowser
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: wsproxy
  namespace: flux-system
spec:
  image: ghcr.io/raiken-mf/wsproxy
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: rathena
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: rathena
  filterTags:
    pattern: '^sha-[a-f0-9]+'
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: robrowser
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: robrowser
  filterTags:
    pattern: '^sha-[a-f0-9]+'
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: wsproxy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: wsproxy
  filterTags:
    pattern: '^sha-[a-f0-9]+'
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: 'chore(k8s): update images automatically [skip ci]'
    push:
      branch: main
  update:
    path: deploy/overlays/flux
    strategy: Setters
