apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ragnarok-stack
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./deploy/overlays/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m0s
  wait: true
